export const userConstants = {
    USER_STORE_KEY: 'lendsqr-fe-test-users',

    RETRIEVING_USER_FROM_STORAGE: 'RETRIEVING_USER_FROM_STORAGE',
    RETRIEVE_USERS_FROM_STORAGE: 'RETRIEVE_USERS_FROM_STORAGE',
    RETRIEVE_USERS_FROM_STORAGE_SUCCESS: 'RETRIEVE_USERS_FROM_STORAGE_SUCCESS',
    RETRIEVE_USERS_FROM_STORAGE_ERROR: 'RETRIEVE_USERS_FROM_STORAGE_ERROR',

    GET_ALL_USERS_SUCCESS_WITHOUT_DATA: 'GET_ALL_USERS_SUCCESS_WITHOUT_DATA',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    REQUESTING_ALL_USERS: 'REQUESTING_ALL_USERS',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',
    GET_ALL_USERS: 'GET_ALL_USERS',

    TOKEN_HAS_EXPIRED: 'TOKEN_HAS_EXPIRED',

    USER_URI: 'https://run.mocky.io/v3/f242ef70-3a75-47bd-890b-0a52c35cdbf6',
}
